trigger: 
- dev

pool: 
  vmImage: ubuntu-image

variables:
    buildConfiguration: 'Release'
steps:
- script: dotnet build --configuration $(buildConfiguration) 
  displayName: 'dotnet build $(buildConfiguration)'