trigger: 
- dev

pool: 
  vmImage: MyAgentPool

variables:
    buildConfiguration: 'Release'
steps:
- script: dotnet build --configuration $(buildConfiguration) 
  displayName: 'dotnet build $(buildConfiguration)'